Improve sample_acf and sample_pacf plots
tinkoff-ai/etna pull request #1004
Opened 2022-11-16 16:46 UTC by DBcreator

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues

closes #682

2022-11-17 10:35 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
>      k = min(n_segments, len(segments))
It seems like it is not really correct. As I understand, we should ignore `n_segments` parameter if `segments` is set. Look at `distribution_plot`.

2022-11-17 10:36 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +            print("yes")
It looks like debug string, remove it.

2022-11-17 10:37 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +        "DeprecationWarning: This function is deprecated and will be removed in etna=1.14.0; Please use acf_plot instead",
I don't really sure about this version of deprecation.

2022-11-17 10:37 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> -        ax[i].grid()
Why is this line removed?

2022-11-17 10:46 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +            warnings.warn("Values with NaN dropped!")
I don't think we should raise this warning. Let's clarify this moment in docstring of the function. Smth like:
```
This function removes any NaNs before plotting.
```

2022-11-17 10:49 UTC, Mr-Geekman commented
I don't see any images about the results of new functions. You should add script for plotting + result images. You should check both `partial=True/False` and data with/without nans. You can look at scripts in #691, #706, https://github.com/tinkoff-ai/etna/milestone/9?closed=1 as a reference.

2022-11-17 10:49 UTC, Mr-Geekman requested changes
Look at comments above.

2022-11-17 15:00 UTC, DBcreator commented
```python3
from etna.analysis import acf_plot
import pandas as pd
import matplotlib.pyplot as plt
from etna.datasets import TSDataset
import warnings 
warnings.filterwarnings("ignore")


data = pd.read_csv("examples/data/nordic_merch_sales.csv")
df = TSDataset.to_dataset(data)
ts = TSDataset(df, freq="D")

acf_plot(ts, n_segments=9, columns_num=3, partial=False)
plt.savefig("Autocorrelation")
acf_plot(ts, n_segments=9, columns_num=3, partial=True)
plt.savefig("Partial Autocorrelation")
```
Autocorrelation:
![изображение](https://user-images.githubusercontent.com/45318525/202480583-77fee729-a057-4995-b0bb-9f68eca61cab.png)

Partial Autocorrelation:
![изображение](https://user-images.githubusercontent.com/45318525/202480795-b755a93e-918d-4f24-bbb8-a4be66e1f022.png)

2022-11-18 09:32 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +        exist_segments = df_pd.segment.unique()
Why can't we write this if like:
```
if segments is None:
    segments = sorted(ts.segments)
    selected_segments = np.random.choice(...)
    segments = list(selected_segments)
```

In this case we don't need `df_pd` variable.

2022-11-18 09:38 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +        "DeprecationWarning: This function is deprecated and will be removed soon; Please use acf_plot instead",
Negotiating about version to be removed.

2022-11-21 13:57 UTC, DBcreator commented
Example with NaN:
```python3
from etna.analysis import acf_plot
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from etna.datasets import TSDataset, generate_const_df, generate_ar_df
import warnings 

df_1 = generate_const_df(periods=100, start_time="2020-01-01", scale=1)
df_1["target"] = [np.nan]*len(df_1["target"])
df_2 = generate_ar_df(periods=100, start_time="2020-04-10")
df = pd.concat([df_1, df_2])

df = TSDataset.to_dataset(df)
ts = TSDataset(df, freq="D")

acf_plot(ts)
plt.savefig("Autocorrelation with NaN.png")

acf_plot(ts, partial=True)
plt.savefig("Partial Autocorrelation with NaN.png")
```
Autocorrelation:
![изображение](https://user-images.githubusercontent.com/45318525/203072829-568ff856-8357-4542-96c8-90949b07bf5e.png)

Partial Autocorrelation:
![изображение](https://user-images.githubusercontent.com/45318525/203072962-e69a2316-7748-47bf-9f52-653265f24bbf.png)

2022-11-21 14:15 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +        if df_slice["target"].isna().any():
Do we need this `if`?

2022-11-22 14:02 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +            indices_nan = np.argwhere(np.isnan(df_slice.values)).squeeze(1)
Try to use [`first_valid_index`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.first_valid_index.html)

2022-11-22 14:03 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +            current_end = len(df_slice.values) - 1
Try to use [`last_valid_index`](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.last_valid_index.html)

2022-11-22 14:04 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +                raise ValueError("There is a NaN in the middle of the time series!")
Errors should be moved to `Raises` block in a docstring. Look at docstring of `cross_corr_plot` for example.

2022-11-24 09:22 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +        df_slice = ts.to_pandas()[name].reset_index()["target"]
Let's move this `to_pandas()` higher to make it only once.

2022-11-24 09:24 UTC, Mr-Geekman commented on etna/analysis/eda_utils.py
> +    This function removes any NaNs from the beginning and end of the series if partial=True.
Write:
```
* If ``partial=False`` function works with NaNs at any place of the time-series.

* if ``partial=True`` function works only with NaNs at the edges of the time-series and fails if there are NaNs inside of it.
```

2022-11-24 10:35 UTC, Mr-Geekman approved these changes

2022-11-25 08:10 UTC, merged