Create `get_level_dataset` method
tinkoff-ai/etna pull request #1053
Opened 2022-12-22 13:49 UTC by brsnw250

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues

closes #1040

2022-12-23 05:12 UTC, alex-hse-repository requested changes

2022-12-23 05:12 UTC, alex-hse-repository commented on etna/datasets/tsdataset.py
> +            current_level_segments = self.hierarchical_structure.get_level_segments(level_name=self.current_df_level)
Place this instead of the "if" checking the existence of `target_level` to make sure that the levels are correct

2022-12-23 05:12 UTC, alex-hse-repository commented on tests/test_datasets/test_hierarchical_dataset.py
> +@pytest.mark.parametrize(
May be just put the fixture names in the signature as there is only one parameters set

2022-12-23 05:12 UTC, alex-hse-repository commented on tests/test_datasets/test_hierarchical_dataset.py
> +@pytest.mark.parametrize(
Change the current fixtures or create separate with
- NaNs in the beginning of some segments
- NaNs in the middle of some segments
We should make sure that everything works with NaNs

2022-12-23 05:12 UTC, alex-hse-repository commented on tests/test_datasets/test_hierarchical_dataset.py
> +@pytest.mark.parametrize(
Also in the separate test use some fixtures for df and df_exog with regressors in the following cases:
1. df and df_exog on the same level and on different level after aggregation
2. df and df_exog on the different levels and on the same level after aggregation

2022-12-23 07:52 UTC, brsnw250 commented on etna/datasets/tsdataset.py
> +        current_level_index = self.hierarchical_structure._level_to_index[self.current_df_level]
Let's add such a method to `HierarchicalStructure`, I think this is a more appropriate place for such a method

2022-12-23 09:39 UTC, alex-hse-repository commented on etna/datasets/tsdataset.py
> +        current_level_index = self.hierarchical_structure._level_to_index[self.current_df_level]
Yes, I was talking about this

2022-12-23 10:02 UTC, brsnw250 commented on etna/datasets/tsdataset.py
> +            target_level_data = target_level_data.astype(source_level_data.dtype)
Fixed type of summing matrics to `int32` so this line no longer relevant

2022-12-24 05:50 UTC, alex-hse-repository requested changes

2022-12-24 05:50 UTC, alex-hse-repository commented on tests/conftest.py
> +def long_hierarchical_structure():
As you use this fixtures only in test_dataset folder better to create the separate `conftest.py` there, here we store the global fixtures. May be later, when we come to test hierarchical pipeline we will move them here

2022-12-24 05:50 UTC, alex-hse-repository commented on tests/test_datasets/test_hierarchical_dataset.py
> +    pd.testing.assert_frame_equal(target_ts.df_exog, estimated_target_ts.df_exog)
The aim of this test is to check that df_exog is merged to df correctly after changing the level of df. So here you should compare the dfs, correct behaviour for the other attributes you can check in the previous test. Text me if you don't get why it is important)

2022-12-24 05:50 UTC, alex-hse-repository commented on tests/test_datasets/test_hierarchical_dataset.py
> +def test_get_level_dataset_with_exog(
Here also add regressor column in df_exog and use parameter `known_future` to pass it. Check that this attribute is also initialized correctly.

2022-12-24 05:50 UTC, alex-hse-repository commented on tests/test_datasets/test_hierarchical_dataset.py
> +def product_level_df_w_nans():
Actually it is better to change the entire fixtures(don't add w_nans prefix) as it is a general case. NaNs in the begging occur almost always. Sorry for suggesting you creating the separate)

2022-12-24 05:50 UTC, alex-hse-repository commented on tests/test_datasets/test_hierarchical_dataset.py
> +            "target": [None, 4, 6, None] + [17, 19, None, 22],
I am not sure that there should be nans, i guess the result should be "None + 3 = 3", but we can discuss it as it is not so obvious(we should come up with some convention for such cases)

2022-12-24 05:50 UTC, alex-hse-repository commented on etna/datasets/tsdataset.py
> +            source_level_data = self.df.loc[:, source_level_index].values
Here it is better to use the implemented `__getitem__`of the dataset as it incapsulates what you have done.
```
 source_level_data = self[:, current_level_segments, "target"].values
```

2022-12-26 11:49 UTC, alex-hse-repository approved these changes

2022-12-26 11:49 UTC, merged