Make `DifferencingTransform` to fail on new segments with understandable error
tinkoff-ai/etna pull request #1141
Opened 2023-03-01 09:00 UTC by Mr-Geekman

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes
Make `DifferencingTransform` to fail on new segments with understandable error in inplace mode.

## Closing issues
Closes #1137.

2023-03-01 12:55 UTC, alex-hse-repository requested changes

2023-03-01 12:55 UTC, alex-hse-repository commented on etna/transforms/math/differencing.py
> +        segments = df.columns.get_level_values("segment").unique().tolist()
Why can we apply transform, but can't apply inverse_transform? May be we also need to diable transform for them?

2023-03-01 12:55 UTC, alex-hse-repository commented on etna/transforms/math/differencing.py
> +    def _validate_segments(self, segments: List[str]):
Looks like come general function which might be helpfull for several transforms, maybe we can put it in utils?

2023-03-03 10:02 UTC, alex-hse-repository requested changes

2023-03-03 10:02 UTC, alex-hse-repository commented on tests/test_transforms/test_math/test_differencing_transform.py
> +    train_df = df_nans.loc[:, pd.IndexSlice["1", :]]
May be crate fixture for this as it is used in many places

2023-03-03 11:12 UTC, Mr-Geekman commented on etna/transforms/math/sklearn.py
>          self._fit_segments = cast(List[str], self._fit_segments)
Mypy fails without this. Yes, I can move it higher.

2023-03-03 11:14 UTC, Mr-Geekman commented on tests/test_transforms/test_inference/test_inverse_transform.py
> +            (DifferencingTransform(in_column="target", inplace=True), "regular_ts"),
With `inplace=False` we have `DifferencingTransform` in `test_inverse_transform_train_new_segments`.

2023-03-03 11:15 UTC, Mr-Geekman commented on tests/test_transforms/test_inference/test_inverse_transform.py
> +            (DifferencingTransform(in_column="target", inplace=True), "regular_ts"),
With `inplace=False` look at `test_inverse_transform_future_new_segments`.

2023-03-03 11:15 UTC, Mr-Geekman commented on tests/test_transforms/test_inference/test_transform.py
> +            (DifferencingTransform(in_column="target", inplace=True), "regular_ts"),
`test_transform_train_new_segments`.

2023-03-06 09:24 UTC, alex-hse-repository requested changes

2023-03-06 09:24 UTC, alex-hse-repository commented on etna/transforms/math/differencing.py
> +        self._fit_segments: Optional[List[str]] = None
Do we need this attribute? You use it only in fit

2023-03-06 09:46 UTC, alex-hse-repository approved these changes

2023-03-06 10:48 UTC, merged