Add target components logic into AutoRegressivePipeline
tinkoff-ai/etna pull request #1188
Opened 2023-03-30 05:54 UTC by alex-hse-repository

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues

closes #1168

2023-03-30 09:09 UTC, brsnw250 requested changes

2023-03-30 09:09 UTC, brsnw250 commented on etna/pipeline/autoregressive_pipeline.py
> +                current_ts_future.drop_target_components()
Can you separate this block with blank lines to make it more readable?

2023-03-30 09:09 UTC, brsnw250 commented on etna/pipeline/autoregressive_pipeline.py
> +            if len(current_ts_future.target_components_names) > 0:
Maybe use just `if return_components `

2023-03-30 14:21 UTC, alex-hse-repository commented on etna/pipeline/autoregressive_pipeline.py
> +        if len(target_components_dfs) > 0:
Same here

2023-03-31 07:34 UTC, brsnw250 approved these changes

2023-03-31 08:26 UTC, merged