Add target components logic into `HierarchicalPipeline`
tinkoff-ai/etna pull request #1199
Opened 2023-03-31 11:45 UTC by brsnw250

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues

2023-04-03 09:02 UTC, alex-hse-repository requested changes

2023-04-03 09:55 UTC, brsnw250 commented on etna/pipeline/mixins.py
> +            hierarchical_structure=ts.hierarchical_structure,
We don't provide any possibility to change `HierarchicalStructure` after creation. So here we can safely use references. Also, in other similar cases, we use reference as well.

2023-04-03 09:55 UTC, brsnw250 commented on tests/test_pipeline/test_hierarchical_pipeline.py
> +def test_forecast_with_return_components(
Here everything works as expected. For `forecast` `DummyModelBase` returns 100 (10 + 90 for forecast components), it is forecast for source `product` level. Also, in this test we do a bottom up reconciliation to obtain values at the target `market` level, so we sum up different segments (X = a + b = 100 + 100 = 200). Same holds for Y segment and components logic.

2023-04-03 09:55 UTC, brsnw250 commented on tests/test_pipeline/test_hierarchical_pipeline.py
> -def test_raw_forecast_with_return_components(product_level_constant_hierarchical_ts):
Generally, they will test the same logic as `predict` and `forecast` in terms of obtaining components. Alternatively, we can test just `raw_predict`  and `raw_forecast`, as they don't perform reconciliation, which is tested separately.

2023-04-03 10:18 UTC, brsnw250 commented on etna/pipeline/hierarchical_pipeline.py
>  from typing import Optional
Added

2023-04-04 09:20 UTC, alex-hse-repository approved these changes

2023-04-04 10:09 UTC, merged