Unifty example notebooks, rerun example notebooks
tinkoff-ai/etna pull request #1330
Opened 2023-07-25 15:57 UTC by Mr-Geekman

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes
Look #1328.

## Closing issues
Closes #1328.

2023-07-26 13:41 UTC, alex-hse-repository requested changes

2023-07-26 14:32 UTC, Mr-Geekman commented on README.md
> +| [Get started](https://github.com/tinkoff-ai/etna/tree/master/examples/01-get_started.ipynb)                                 |                [![Binder](https://mybinder.org/badge_logo.svg)](https:/
Because I fixed the links to have number in them.

2023-07-26 14:33 UTC, Mr-Geekman commented on README.md
> +| [Get started](https://github.com/tinkoff-ai/etna/tree/master/examples/01-get_started.ipynb)                                 |                [![Binder](https://mybinder.org/badge_logo.svg)](https:/
They will have numbers if this track will end in `master` branch.

2023-07-26 14:34 UTC, Mr-Geekman commented on docs/source/conf.py
> +    <style>
Because otherwise tables look poor. I thought we already discussed that.

2023-07-26 14:34 UTC, Mr-Geekman commented on examples/README.md
> +# Examples
I think it is a good idea, probably we should do this in another task.

2023-07-26 14:34 UTC, Mr-Geekman commented on examples/README.md
> +### 01. [Get started](https://github.com/tinkoff-ai/etna/tree/master/examples/01-get_started.ipynb)
Because I corrected links to have numbers, they will start work after merging the track into master.

2023-07-26 14:36 UTC, Mr-Geekman commented on pyproject.toml
> +nbqa = {extras = ["isort"], version = "^1.7.0", optional = true}
We are already using `black` for the notebooks. May be we could add `flake8`, but I'm not sure about it.

2023-07-26 15:24 UTC, Mr-Geekman commented on CONTRIBUTING.md
>  ### Before the PR
Ok, will be done.

2023-07-26 15:29 UTC, Mr-Geekman commented on CONTRIBUTING.md
> +#### Building
Same, it is a part of documentation section.

2023-07-31 07:12 UTC, alex-hse-repository requested changes

2023-07-31 07:12 UTC, alex-hse-repository commented on CONTRIBUTING.md
> +#### Adding tutorials (optional)
May be 7.1

2023-07-31 07:12 UTC, alex-hse-repository commented on pyproject.toml
> +nbqa = {extras = ["isort"], version = "^1.7.0", optional = true}
We can try))

2023-07-31 07:12 UTC, alex-hse-repository commented on examples/14-hierarchical_pipeline.ipynb
>     "cell_type": "markdown",
<p>Why did the metrics change?</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1330/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='80'/>

2023-07-31 07:18 UTC, alex-hse-repository commented
Better, but still looks a little bit wierd
<img width="759" alt="Снимок экрана 2023-07-31 в 10 17 49" src="https://github.com/tinkoff-ai/etna/assets/55380696/dc330e51-4c07-4c50-86ca-8913c5654735">

2023-07-31 07:18 UTC, Mr-Geekman commented on CONTRIBUTING.md
> +4. List extensions that are necessary for this notebook to run.
For notebooks without extensions this block is just one small line.

2023-07-31 07:19 UTC, alex-hse-repository commented
Table of contents works only for the first level in the notebooks

2023-07-31 07:19 UTC, Mr-Geekman commented on pyproject.toml
> +nbqa = {extras = ["isort"], version = "^1.7.0", optional = true}
I don't think that flake8 checks are necessary there and `black` is enough.

2023-07-31 07:23 UTC, Mr-Geekman commented
<p>In the beginning we have </p><p> </p><blockquote>ts = TSDataset(df, freq="1M")</blockquote><p> </p><p>where we expect warning to happen.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1330/discussion/#comment-1657796162'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-07-31 07:26 UTC, Mr-Geekman commented
<p>Because it produced some output that I didn't want to show. </p><p> </p><p>We can uncomment it, it isn't that necessary.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1330/discussion/#comment-1657796292'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-07-31 07:46 UTC, Mr-Geekman commented
<p>It is very strange. It looks normal if you view it on github.</p><p> </p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1330/discussion/#comment-1657796318'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-07-31 07:58 UTC, Mr-Geekman commented
<p>I don't think it is necessary. It is a part of <code>DirectEnsemble</code>, not a separate section by its meaning.  </p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1330/discussion/#comment-1657796362'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-07-31 08:02 UTC, Mr-Geekman commented
<p>Will be fixed.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1330/discussion/#comment-1657796412'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-07-31 08:03 UTC, Mr-Geekman commented
<p>Because it was running on a different machine.</p>

---

 <a href='https://app.reviewnb.com/tinkoff-ai/etna/pull/1330/discussion/#comment-1657796437'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

2023-08-01 11:56 UTC, alex-hse-repository approved these changes

2023-08-01 12:27 UTC, merged