Closes #290
tinkoff-ai/etna pull request #313
Opened 2021-11-24 12:01 UTC by Carlosbogo

Renames parameters for number of folds in different functions to keep naming consistency

2021-11-24 16:07 UTC, iKintosh commented
As I can see you didn't change tests, that's why test workflow fails: https://github.com/tinkoff-ai/etna/runs/4313774890?check_suite_focus=true#step:8:920
You may run tests locally to catch all errors.

2021-11-24 16:10 UTC, iKintosh requested changes
Also need changes to tests.

2021-11-25 18:53 UTC, Carlosbogo commented
Sorry, but I don't quite understand. Could you give me an example on what I need to change in the tests so that they work properly?

2021-11-26 14:03 UTC, iKintosh commented
Sure. Happy to do that!

So you have changed pipeline and stacking ensemble classes. You renamed `cv` to `n_folds`. But we are testing this functionality in several tests.

As you can see, here we try to call stacking ensemble class with several `cv` parameters, however now it is called `n_folds`:
https://github.com/tinkoff-ai/etna/blob/master/tests/test_ensembles/test_stacking_ensemble.py#L41

So in order to make it it work again you should change `cv` to `n_folds` in tests as well.

You can find all test that are testing stacking ensemble class here https://github.com/tinkoff-ai/etna/blob/master/tests/test_ensembles/test_stacking_ensemble.py
And all tests that are testing pipeline class here https://github.com/tinkoff-ai/etna/tree/master/tests/test_pipeline

2021-11-27 16:13 UTC, iKintosh approved these changes
Thanks!
🎉 🚀

2021-11-27 20:03 UTC, merged

2021-11-28 15:57 UTC, Carlosbogo commented
Thank you for your feedback and for guiding me through the PR process! I hope it helps.