Categorical encoders
tinkoff-ai/etna pull request #431
Opened 2021-12-30 07:28 UTC by Ama16

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes

## Related Issue

## Closing issues

2021-12-30 08:13 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +            - If "new_value", then replace missing dates with '-1'
It seems like "dates" isn't valid here.

2021-12-30 08:16 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +    def transform(self, y: pd.Series, strategy):
It is better to create Enum class like in other cases like [this](https://github.com/tinkoff-ai/etna/blob/master/etna/transforms/missing_values/imputation.py)

2021-12-30 09:28 UTC, iKintosh commented on etna/transforms/encoders/categorical.py
> +            - If "new_value", then replace missing dates with '-1'
better to use `timestamps`

2021-12-30 09:39 UTC, iKintosh requested changes
Mostly okay. But need some changes. 

Kind reminder: if you think that PR is not ready for merge you should make it a draft)

2021-12-30 09:39 UTC, iKintosh commented on etna/transforms/encoders/categorical.py
> +class LE(preprocessing.LabelEncoder):
Make it `_LabelEncoder`, because this class is not intended for users and longer name makes it easier to understand class meaning.

2021-12-30 09:39 UTC, iKintosh commented on etna/transforms/encoders/categorical.py
> +    """Replace the values in the column with the Label encoding"""
There is no `inverse transform` method on purpose?

2021-12-30 09:39 UTC, iKintosh commented on etna/transforms/encoders/categorical.py
> +            - If "new_value", then replace missing dates with '-1'
better to use `values` here

2021-12-30 09:39 UTC, iKintosh commented on etna/transforms/encoders/categorical.py
> +    def _get_out_column(self, out_column: Optional[str]) -> str:
it should be named `get_column_name` as in other transforms

2021-12-30 09:39 UTC, iKintosh commented on etna/transforms/encoders/categorical.py
> +###############################
Do we need to review what's below this line?

2022-01-11 14:32 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +            temp_transform = LabelBinarizerTransform(in_column=self.in_column, out_column=self.out_column)
Can't we use here just `self.__repr__`?

2022-01-11 14:33 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +class LabelBinarizerTransform(PerSegmentWrapper):
Add description to the class. What is its purpose.

2022-01-11 14:41 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +    df1 = TSDataset.to_dataset(generate_periodic_df(3, "2020-01-01", 10, 2, n_segments=2))
Use named parameters here because it is not obvious what is the meaning of all these parameters.

2022-01-11 15:14 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +            if True, apply resampling inplace to in_column, if False, add transformed column to dataset
Resampling is irrelevant here

2022-01-11 15:19 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +            transform=_OneSegmentLabelEncoderTransform(self.in_column, self.out_column, self.strategy, self.inplace)
Use keyword parameters here like in_column=self.in_column.
This can be a reason for warning during creation with out_column=None.

2022-01-12 12:32 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +            temp_transform = LabelEncoderTransform(
What is about this?

2022-01-12 12:33 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +        if strategy == "None":
Threre is no such value as "None", only "none", may be better to check this using Enum type, not manually.

2022-01-12 12:35 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +    """Test LabelEncoderTransform correct works."""
I think, that better description is:
"Test that LabelEncoderTransform works correct"

2022-01-12 13:05 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +def test_new_value_label(two_df_with_new_values, strategy, expected_values):
label_encoder in the name of the test is omitted.

same issue with word order in description

2022-01-12 13:06 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +def test_label_encoder(df_for_categorical_encoding):
May be better to name "test_label_encoder_simple"

2022-01-12 13:07 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +    """Test LabelEncoderTransform correct works."""
It will be more correct to use
"Test that LabelEncoderTransform works correct in simple case."

2022-01-12 13:17 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +class OneHotEncoderTransform(PerSegmentWrapper):
Describe how it works with new values.

2022-01-14 07:20 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +    If unknown category is encountered during transform, the resulting one-hot encoded columns for this feature will be all zeros.
It seems like we have to add empty line after the first line with short description: [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html#docstring-standard).

2022-01-14 07:21 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +    assert 1 - r2(forecast_ts, test_ts)["segment_0"] < 1e-5
In metric we expect `y_true` to be the first parameter.

2022-01-14 07:23 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +def test_ohe_sanity(ts_for_ohe_sanity):
I think we should
1. Add description to the test.
2. Move it to the very of the file (fixture should be moved to the end of fixtures for this file).

2022-01-14 07:27 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +    train_ts, test_ts = ts.train_test_split(test_size=10)
I think we should move train_test_split into the test, because they have the same parameter horizon=10.

2022-01-14 07:33 UTC, Mr-Geekman commented on tests/test_transforms/test_encoders/test_categorical_transform.py
> +    df_to_forecast = generate_ar_df(100, start_time="2021-01-01", n_segments=1)
Add periods parameter in cases like this.

2022-01-14 08:14 UTC, Mr-Geekman commented on etna/transforms/encoders/categorical.py
> +        super().__init__(transform=_OneSegmentLabelEncoderTransform(self.in_column, self.out_column, self.strategy))
Use keyword parameters to create object.

2022-01-17 17:39 UTC, iKintosh submitted a review, later dismissed
Seems like everything is okay.

2022-01-18 08:56 UTC, Mr-Geekman approved these changes

2022-01-18 08:56 UTC, merged