plot trend
tinkoff-ai/etna pull request #565
Opened 2022-02-22 09:29 UTC by Ama16

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes

## Related Issue

## Closing issues

closes #515

2022-02-22 09:30 UTC, Ama16 commented
<img width="994" alt="Снимок экрана 2022-02-22 в 12 23 49" src="https://user-images.githubusercontent.com/48079881/155103174-5cb32244-df95-4350-9742-f15239bd6da0.png">
<img width="994" alt="Снимок экрана 2022-02-22 в 12 24 09" src="https://user-images.githubusercontent.com/48079881/155103188-ad500106-bf90-4a8e-be66-1762999b6b78.png">
<img width="994" alt="Снимок экрана 2022-02-22 в 12 24 24" src="https://user-images.githubusercontent.com/48079881/155103193-931e3621-1b95-46ce-af39-5f960090a3e2.png">
<img width="994" alt="Снимок экрана 2022-02-22 в 12 24 38" src="https://user-images.githubusercontent.com/48079881/155103199-d9c2d519-c5fd-4070-855d-0ee08fc8cf9c.png">

2022-02-24 13:25 UTC, iKintosh requested changes

2022-02-24 13:25 UTC, iKintosh commented on etna/analysis/plotters.py
> +    from etna.transforms import TheilSenTrendTransform
Why are these lines here?

2022-02-24 13:25 UTC, iKintosh commented on etna/analysis/plotters.py
> +                linear_coeffs[seg] = ", k=" + str(trend_transform.segment_transforms[seg]._linear_model.coef_[0])
Does it mean, that we can see coefficient of linear model only if we use it alone?

2022-02-24 13:25 UTC, iKintosh commented on etna/analysis/plotters.py
> +            labels = labels_short
This seems like we need this "if" only in some cases, because some transforms do not have short labels. Right?

2022-02-24 14:32 UTC, iKintosh requested changes
Added comments on how it should be changed

2022-02-24 14:32 UTC, iKintosh commented on etna/analysis/plotters.py
> +            labels = labels_short
Let's make it a private method, that constructs labels. 
It should have small docsting on how it works:
```
If only unique transform classes then show their short names (without parameters)
If  not, then show their full repr as label
```

2022-02-24 14:32 UTC, iKintosh commented on etna/analysis/plotters.py
> +        labels = [trend_transform.__repr__()[: trend_transform.__repr__().find("(")]]
Remove this `else` because it repeats the code above.

2022-02-24 14:32 UTC, iKintosh commented on etna/analysis/plotters.py
> +                linear_coeffs[seg] = ", k=" + str(trend_transform.segment_transforms[seg]._linear_model.coef_[0])
This check should be done afterwards as a separate check.

2022-03-01 15:43 UTC, iKintosh requested changes
Just one fix needed

2022-03-01 15:43 UTC, iKintosh commented on etna/analysis/plotters.py
> +def __get_labels_names(trend_transform, segments):
```suggestion
def _get_labels_names(trend_transform, segments):
```

[No double ](https://stackoverflow.com/a/1301369/7415703)

2022-03-01 15:43 UTC, iKintosh commented on etna/analysis/plotters.py
> +    labels, linear_coeffs = __get_labels_names(trend_transform, segments)
```suggestion
    labels, linear_coeffs = _get_labels_names(trend_transform, segments)
```
Same as above https://stackoverflow.com/a/1301369/7415703

2022-03-09 08:08 UTC, Ama16 commented
<img width="968" alt="Снимок экрана 2022-03-09 в 11 03 23" src="https://user-images.githubusercontent.com/48079881/157399123-db330e03-8d9c-400f-bdbc-51e75629acba.png">

2022-03-09 08:47 UTC, iKintosh approved these changes
👍

2022-03-09 11:11 UTC, merged