Add `plot_features_relevance`
tinkoff-ai/etna pull request #579
Opened 2022-03-02 15:21 UTC by Mr-Geekman

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes
Look #564.

## Related Issue
#564.

## Closing issues
Closes #564.

2022-03-02 15:35 UTC, Mr-Geekman commented
Script for demonstration:
```python
from typing import Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from etna.analysis import StatisticsRelevanceTable
from etna.analysis import plot_feature_relevance
from etna.datasets import TSDataset


def simple_df_relevance() -> Tuple[pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(42)
    timestamp = pd.date_range("2021-01-01", "2021-02-01")

    df_1 = pd.DataFrame({"timestamp": timestamp, "target": np.arange(32), "segment": "1"})
    df_2 = pd.DataFrame({"timestamp": timestamp[5:], "target": np.arange(5, 32), "segment": "2"})
    df = pd.concat([df_1, df_2], ignore_index=True)
    df = TSDataset.to_dataset(df)

    timestamp = pd.date_range("2020-12-01", "2021-02-11")

    df_1 = pd.DataFrame(
        {
            "timestamp": timestamp,
            "regressor_1": np.arange(len(timestamp)),
            "regressor_2": np.zeros(len(timestamp)),
            "regressor_3": rng.normal(loc=0, scale=1.0, size=len(timestamp)),
            "regressor_4": rng.uniform(low=0, high=10.0, size=len(timestamp)),
            "regressor_5": rng.exponential(scale=1.0, size=len(timestamp)),
            "cat_feature": "hello",
            "segment": "1",
        }
    )
    df_2 = pd.DataFrame(
        {
            "timestamp": timestamp[5:],
            "regressor_1": np.sin(-np.arange(len(timestamp) - 5)),
            "regressor_2": np.log(np.arange(1, len(timestamp) - 4)),
            "regressor_3": rng.normal(loc=0, scale=2.0, size=len(timestamp) - 5),
            "regressor_4": rng.uniform(low=0, high=5.0, size=len(timestamp) - 5),
            "regressor_5": rng.exponential(scale=0.1, size=len(timestamp) - 5),
            "cat_feature": "bye",
            "segment": "2",
        }
    )
    df_exog = pd.concat([df_1, df_2], ignore_index=True)
    df_exog = TSDataset.to_dataset(df_exog)

    return df, df_exog


df, df_exog = simple_df_relevance()
ts = TSDataset(df=df, df_exog=df_exog, known_future="all", freq="D")
relevance_table = StatisticsRelevanceTable()

plot_feature_relevance(
    ts=ts,
    relevance_table=relevance_table,
    normalized=False,
    relevance_aggregation_mode="per-segment",
    top_k=None,
    segments=None,
    columns_num=2,
    figsize=(10, 5),
)

plt.savefig("per-segment.png")

plot_feature_relevance(
    ts=ts,
    relevance_table=relevance_table,
    normalized=False,
    relevance_aggregation_mode="mean",
    top_k=None,
    segments=None,
    columns_num=2,
    figsize=(10, 5),
)

plt.savefig("mean.png")
```

mean:
![mean](https://user-images.githubusercontent.com/36005824/156394144-5a0a8503-58f1-49e6-b2ad-ec94e98ced5c.png)

per-segment:
![per-segment](https://user-images.githubusercontent.com/36005824/156394174-aee19d6d-dd06-4976-b506-84e393c09acd.png)

2022-03-09 09:52 UTC, alex-hse-repository requested changes
May you also try to test this method in the different combinations of the parameters(different relevance tables, normalization, top_k, aggregation mod)

2022-03-09 09:52 UTC, alex-hse-repository commented on etna/analysis/plotters.py
> +        aggregation strategy for obtained feature relevance table
May be it is better to list the possible variants of aggregation

2022-03-09 09:52 UTC, alex-hse-repository commented on etna/analysis/plotters.py
> +    relevance_df = relevance_table(df=ts[:, :, "target"], df_exog=ts.df_exog).loc[segments]
df_exog does not contain all the features in the dataset, you need to use `ts[:,:,features]` here, where `features = set(ts.columns.get_level_values("feature")) - set(["target"])`

2022-03-09 09:52 UTC, alex-hse-repository commented on etna/analysis/plotters.py
> +):
Add somewhere `**relevance_params` because `ModelRelevanceTable` requires the model to be specified

2022-03-09 09:52 UTC, alex-hse-repository commented on etna/analysis/plotters.py
> +    Plot relevance of the features.
May you clarify that the features on the plot are order in descending order of their importance

2022-03-09 09:52 UTC, alex-hse-repository commented on etna/analysis/plotters.py
> +        relevance = relevance.dropna()[:top_k]
May be let's throw warning that we are not able to calculate the relevance of some features

2022-03-09 16:15 UTC, Mr-Geekman commented
Скрипт:
```python
from typing import Tuple

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor

from etna.analysis import ModelRelevanceTable
from etna.analysis import StatisticsRelevanceTable
from etna.analysis import plot_feature_relevance
from etna.datasets import TSDataset
from etna.transforms import DateFlagsTransform
from etna.transforms import FilterFeaturesTransform


def simple_df_relevance() -> Tuple[pd.DataFrame, pd.DataFrame]:
    rng = np.random.default_rng(42)
    timestamp = pd.date_range("2021-01-01", "2021-02-01")

    df_1 = pd.DataFrame({"timestamp": timestamp, "target": np.arange(32), "segment": "1"})
    df_2 = pd.DataFrame({"timestamp": timestamp[5:], "target": np.arange(5, 32), "segment": "2"})
    df = pd.concat([df_1, df_2], ignore_index=True)
    df = TSDataset.to_dataset(df)

    timestamp = pd.date_range("2020-12-01", "2021-02-11")

    df_1 = pd.DataFrame(
        {
            "timestamp": timestamp,
            "regressor_1": np.arange(len(timestamp)),
            "regressor_2": np.zeros(len(timestamp)),
            "regressor_3": rng.normal(loc=0, scale=1.0, size=len(timestamp)),
            "regressor_4": rng.uniform(low=0, high=10.0, size=len(timestamp)),
            "regressor_5": rng.exponential(scale=1.0, size=len(timestamp)),
            "cat_feature": "hello",
            "segment": "1",
        }
    )
    df_2 = pd.DataFrame(
        {
            "timestamp": timestamp[5:],
            "regressor_1": np.sin(-np.arange(len(timestamp) - 5)),
            "regressor_2": np.log(np.arange(1, len(timestamp) - 4)),
            "regressor_3": rng.normal(loc=0, scale=2.0, size=len(timestamp) - 5),
            "regressor_4": rng.uniform(low=0, high=5.0, size=len(timestamp) - 5),
            "regressor_5": rng.exponential(scale=0.1, size=len(timestamp) - 5),
            "cat_feature": "bye",
            "segment": "2",
        }
    )
    df_exog = pd.concat([df_1, df_2], ignore_index=True)
    df_exog = TSDataset.to_dataset(df_exog)

    return df, df_exog


def main():
    df, df_exog = simple_df_relevance()
    ts = TSDataset(df=df, df_exog=df_exog, known_future="all", freq="D")
    statistics_relevance_table = StatisticsRelevanceTable()
    model_relevance = RandomForestRegressor(n_estimators=100, random_state=42)
    model_relevance_table = ModelRelevanceTable()

    plot_feature_relevance(
        ts=ts,
        relevance_table=statistics_relevance_table,
        normalized=False,
        relevance_aggregation_mode="per-segment",
        top_k=None,
        segments=None,
        columns_num=2,
        figsize=(10, 5),
    )

    plt.savefig("per-segment.png")

    plot_feature_relevance(
        ts=ts,
        relevance_table=statistics_relevance_table,
        normalized=False,
        relevance_aggregation_mode="mean",
        top_k=None,
        segments=None,
        columns_num=2,
        figsize=(10, 5),
    )

    plt.savefig("mean.png")

    transforms = [
        FilterFeaturesTransform(exclude=["cat_feature"]),
        DateFlagsTransform(day_number_in_week=True, day_number_in_month=True, is_weekend=True, out_column="date_flag"),
    ]
    ts.fit_transform(transforms)

    plot_feature_relevance(
        ts=ts,
        relevance_table=model_relevance_table,
        normalized=False,
        relevance_aggregation_mode="per-segment",
        relevance_params={"model": model_relevance},
        top_k=5,
        segments=None,
        columns_num=2,
        figsize=(10, 5),
    )

    plt.savefig("random_forest_per_segment.png")

    plot_feature_relevance(
        ts=ts,
        relevance_table=model_relevance_table,
        normalized=False,
        relevance_aggregation_mode="mean",
        relevance_params={"model": model_relevance},
        top_k=5,
        segments=None,
        columns_num=2,
        figsize=(10, 5),
    )

    plt.savefig("random_forest_mean.png")

    plot_feature_relevance(
        ts=ts,
        relevance_table=model_relevance_table,
        normalized=True,
        relevance_aggregation_mode="mean",
        relevance_params={"model": model_relevance},
        top_k=5,
        segments=None,
        columns_num=2,
        figsize=(10, 5),
    )

    plt.savefig("random_forest_mean_normalized.png")


if __name__ == "__main__":
    main()
```

Статистическая таблица, по сегментам:
![per-segment](https://user-images.githubusercontent.com/36005824/157482750-07bed6f2-ff56-402c-acb4-d70e04697d06.png)

Статистическая таблица, усреднение: 
 ![mean](https://user-images.githubusercontent.com/36005824/157482779-17049c0e-a2e8-4234-80fa-52abbc3a32c7.png)

Таблица по модели, по сегментам:
![random_forest_per_segment](https://user-images.githubusercontent.com/36005824/157482848-e71c62ac-93d4-421d-9f4d-bb5d377270a6.png)

Таблица по сегментам, усреднение: 
![random_forest_mean](https://user-images.githubusercontent.com/36005824/157482872-6c3bcb50-e7f3-4353-8e15-12e2a7f4a5c5.png)

Таблица по сегментам, усреднение с нормализацией:
![random_forest_mean_normalized](https://user-images.githubusercontent.com/36005824/157482890-a014c439-d8b6-4031-8db7-9b374eaef2b3.png)

2022-03-10 05:12 UTC, alex-hse-repository approved these changes

2022-03-10 05:12 UTC, merged