POC nets x tsdataset
tinkoff-ai/etna pull request #620
Opened 2022-03-22 21:01 UTC by martins0n

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes

## Related Issue

## Closing issues

2022-05-12 13:38 UTC, iKintosh requested changes
Everything looks good. But need to add typings and fix style problems.

2022-05-12 13:38 UTC, iKintosh commented on etna/datasets/tsdataset.py
> +        ]
This is a full duplicate of https://github.com/tinkoff-ai/etna/blob/bbf6f9603c406379a582d6c9f940899535c8979e/etna/datasets/tsdataset.py#L1135-L1141

2022-05-12 13:38 UTC, iKintosh commented on etna/datasets/tsdataset.py
> +    def to_train_dataloader(self, encoder_length, decoder_length, columns_to_add, batch_size: int = 1):
Typings are necessary.

2022-05-12 13:38 UTC, iKintosh commented on etna/datasets/tsdataset.py
> +def make_samples(x: dict, encoder_length, decoder_length, columns_to_add):
Also typings

2022-05-12 13:38 UTC, iKintosh commented on etna/datasets/tsdataset.py
> +    def to_test_dataloader(self, encoder_length, decoder_length, columns_to_add, batch_size: int = 1):
Also typings. They are needed not only for parameters but for output of the methods as well.

2022-05-12 13:38 UTC, iKintosh commented on etna/models/nn/utils.py
> +    target: torch.Tensor
Why not use dataclass? 
https://docs.python.org/3/library/dataclasses.html

2022-07-21 09:29 UTC, martins0n commented
closed in #776

2022-07-21 09:29 UTC, closed without merging