Add Per-segment metric visualization
tinkoff-ai/etna pull request #658
Opened 2022-04-22 14:03 UTC by Mr-Geekman

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes
Look #545.

## Related Issue
#545.

## Closing issues
Closes #545.

2022-04-22 14:05 UTC, Mr-Geekman commented
Example script:
```python
import matplotlib.pyplot as plt
import pandas as pd

from etna.analysis import plot_metric_per_segment
from etna.datasets import TSDataset
from etna.metrics import MAE
from etna.metrics import SMAPE
from etna.models import ProphetModel
from etna.pipeline import Pipeline


def main():
    df = pd.read_csv("examples/data/example_dataset.csv", parse_dates=["timestamp"])
    df_wide = TSDataset.to_dataset(df)
    ts = TSDataset(df=df_wide, freq="D")

    pipeline = Pipeline(model=ProphetModel(), horizon=10)
    metrics_df, _, _ = pipeline.backtest(ts=ts, n_folds=3, metrics=[MAE(), SMAPE()])

    plot_metric_per_segment(metrics_df=metrics_df, metric_name="MAE", per_fold_aggregation_mode="mean")
    plt.savefig("metric_per_segment_plot")

    pipeline = Pipeline(model=ProphetModel(), horizon=10)
    metrics_df, _, _ = pipeline.backtest(ts=ts, n_folds=3, metrics=[MAE(), SMAPE()])

    plot_metric_per_segment(
        metrics_df=metrics_df, metric_name="MAE", per_fold_aggregation_mode="mean", ascending=True, top_k=2
    )
    plt.savefig("metric_per_segment_plot_limited")


if __name__ == "__main__":
    main()
```

metric_per_segment_plot:
![metric_per_segment_plot](https://user-images.githubusercontent.com/36005824/164730531-87d11bca-3e4b-42bf-a433-bf1b321be685.png)

metric_per_segment_plot_limited:
![metric_per_segment_plot_limited](https://user-images.githubusercontent.com/36005824/164730551-85a755f4-519e-491b-81e9-22ca40fd3792.png)

2022-04-28 09:34 UTC, iKintosh requested changes
It seem I have found a bug =)

2022-04-28 09:34 UTC, iKintosh commented on etna/analysis/plotters.py
> +            return self.nanmedian
Are you sure it is `self.nanmedian` and not `np.nanmedian`?

2022-04-29 09:10 UTC, iKintosh approved these changes

2022-04-29 10:25 UTC, merged