Fix bugs and documentation for `cross_corr_plot`
tinkoff-ai/etna pull request #691
Opened 2022-05-13 10:29 UTC by Mr-Geekman

**IMPORTANT: Please do not create a Pull Request without creating an issue first.**

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Type of Change

- [ ] Examples / docs / tutorials / contributors update
- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] Improvement (non-breaking change which improves an existing feature)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Proposed Changes
Look #663.

## Related Issue
#663.

## Closing issues
Closes #663.

2022-05-13 10:33 UTC, Mr-Geekman commented
Example script:
```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from etna.datasets import TSDataset
from etna.analysis import cross_corr_plot


def main():
    df = pd.read_csv("examples/data/example_dataset.csv")
    df = TSDataset.to_dataset(df)
    ts = TSDataset(df, freq="D")

    cross_corr_plot(ts=ts, n_segments=6, columns_num=2, maxlags=20)
    plt.savefig("plot_columns_num_2.png")

    cross_corr_plot(ts=ts, n_segments=6, columns_num=3, maxlags=20)
    plt.savefig("plot_columns_num_3.png")

    cross_corr_plot(ts=ts, segments=["segment_a", "segment_b", "segment_c"], maxlags=20)
    plt.savefig("plot_set_segments.png")

    # add some NaNs at the beginning of one segment
    df.iloc[:5, 0] = np.NaN
    ts = TSDataset(df, freq="D")
    cross_corr_plot(ts=ts, maxlags=20)
    plt.savefig("plot_nans_beginning.png")

    # add some NaNs at the center of one segment
    df.iloc[10, 1] = np.NaN
    ts = TSDataset(df, freq="D")
    cross_corr_plot(ts=ts, maxlags=20)
    plt.savefig("plot_nans_middle.png")


if __name__ == "__main__":
    main()
```

plot_columns_num_2:
![plot_columns_num_2](https://user-images.githubusercontent.com/36005824/168265960-64053022-644e-4eda-82d5-37b015cb5e69.png)

plot_columns_num_3:
![plot_columns_num_3](https://user-images.githubusercontent.com/36005824/168265983-9d839337-0d7e-4868-a1a6-639a5d4a6d8c.png)

plot_set_segments:
![plot_set_segments](https://user-images.githubusercontent.com/36005824/168266006-1bb56372-a284-4e07-8763-e165a659c002.png)

plot_nans_beginning:
![plot_nans_beginning](https://user-images.githubusercontent.com/36005824/168266030-c08f0f48-613d-4bff-9392-dd78cdb97e89.png)

plot_nans_middle:
![plot_nans_middle](https://user-images.githubusercontent.com/36005824/168266046-8d517f87-3d2e-4a4d-a94e-b8101160d368.png)

2022-05-17 11:21 UTC, alex-hse-repository requested changes

2022-05-17 11:21 UTC, alex-hse-repository commented on etna/analysis/eda_utils.py
> +def _cross_correlation(
Try to rewrite this method using `np.convolve` to compute correlation and norms

2022-05-17 12:57 UTC, alex-hse-repository approved these changes
👍

2022-05-17 13:04 UTC, merged