Create assemble_pipelines 717
tinkoff-ai/etna pull request #774
Opened 2022-06-27 14:20 UTC by scanhex12

## Before submitting (must do checklist)

- [ ] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [ ] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues

closes #717

2022-07-05 07:37 UTC, iKintosh requested changes
Code looks good, however it does not work as stated in the issue description. 

It should match not only model-horizon, but transforms-models in case if we want different transform for different models. The example of this behaviour could be seen in the issue description. 

Important note: if we want to skip transform for the model we use None instead

```
assemble_pipelines([Catboost(), Prophet()], [TrendTransform(in_column="target"), [LagTransform(lags=[1,2,3], in_column="target"), **None**], [1, 2])

Pipeline(model=Catboost(), transforms=[TrendTransform(in_column="target"), LagTransform(lags=[1,2,3], in_column="target")], horizon=1)
Pipeline(model=Prophet(), transforms=[TrendTransform(in_column="target")], horizon=2)
```

Also there are not enough test. 
You should add test case if we have different models for different horizons, as well as different transforms for different models.

2022-07-05 07:37 UTC, iKintosh commented on etna/pipeline/assemble_pipelines.py
> +    transforms: Sequence[Transform],
It should be able to work with cases such as 

```
assemble_pipelines(Catboost(), [TrendTransform(in_column="target"), [LagTransform(lags=[1,2,3], in_column="target"), LagTransform(lags=[2,3,4], in_column="target")]], [1, 2])
```

And as a result it should create the following two pipelines:

```
Pipeline(model=Catboost(), transforms=[TrendTransform(in_column="target"), LagTransform(lags=[1,2,3], in_column="target")], horizon=1)
Pipeline(model=Catboost(), transforms=[TrendTransform(in_column="target"), LagTransform(lags=[2,3,4], in_column="target")], horizon=2)
```

2022-07-05 07:37 UTC, iKintosh commented on tests/test_pipeline/test_assemble_pipelines.py
> +def test_not_equal_lengths():
Good idea for test! 👍

2022-07-13 08:13 UTC, Mr-Geekman commented
Function `assemble_pipelines` can't be found in documentation after building it. Try not to name function and file with the same name, there can be a confusion for `Sphynx`.

2022-07-13 08:18 UTC, Mr-Geekman commented
Try not to touch `poetry.lock` file. Try to regenerate it in your case with `poetry lock --no-update` command and check if it is still add new line at the end.

2022-07-13 08:20 UTC, Mr-Geekman commented on CHANGELOG.md
> +- assemble pipelines ([#717](https://github.com/tinkoff-ai/etna/issues/717))
We usually add PRs to CHANGELOG.md, not Issues, change it here to https://github.com/tinkoff-ai/etna/pull/774.

2022-07-13 09:50 UTC, iKintosh reviewed
I think it looks good. But I need some clarifications about checks of same length.

2022-07-13 09:50 UTC, iKintosh commented on etna/pipeline/assemble_pipelines.py
> +    for transform in transforms:
This naming considered bad practice. Since it is hard to tell `transform` and `transforms` apart.

2022-07-13 09:50 UTC, iKintosh commented on etna/pipeline/assemble_pipelines.py
> +            if n_transforms != 1 and len(transform) != n_transforms:
Shouldn't we check here for `len(transform) != n_models`?

2022-07-13 10:40 UTC, iKintosh commented
Also @Mr-Geekman has some questions about `test_not_equal_lengths`. Please take a look at it. We guess that every test case is valid.

2022-07-14 09:04 UTC, Mr-Geekman commented on etna/pipeline/assmbling_pipelines.py
> +        Sequence of the transforms
I think we should explain here how broadcasting is made. It is not obvious.

2022-07-14 09:05 UTC, Mr-Geekman commented on etna/pipeline/assmbling_pipelines.py
> +
Or we should add description about broadcasting here.

2022-07-14 09:13 UTC, iKintosh commented on etna/pipeline/__init__.py
> +from etna.pipeline.pipelines_fabric import assemble_pipelines
`pipeline_assembling`

2022-07-14 09:31 UTC, iKintosh approved these changes
Looks good. Ready to merge. Fixed import errors.

2022-07-14 09:31 UTC, iKintosh commented on etna/pipeline/assembling_pipelines.py
> +    Examples
👍 
This is a good practice

2022-07-14 11:24 UTC, merged