[WIP] Rename catboost
tinkoff-ai/etna pull request #779
Opened 2022-07-04 09:25 UTC by julia-shenshina

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues
closes #737

2022-07-04 09:55 UTC, Mr-Geekman commented on etna/models/catboost.py
>      >>> model = CatBoostModelPerSegment()
Вот тут должна быть новая модель.

2022-07-04 09:56 UTC, Mr-Geekman commented on etna/models/catboost.py
>      >>> model = CatBoostModelMultiSegment()
Same about new name

2022-07-04 10:07 UTC, julia-shenshina commented on etna/models/catboost.py
>      >>> model = CatBoostModelPerSegment()
why? 

examples for class usage should be about the class they rely to, shouldn't they?
I added a warning that refers to a new class to docs and corresponding example to a new class 🤔

2022-07-04 10:08 UTC, julia-shenshina commented on etna/models/catboost.py
>      >>> model = CatBoostModelPerSegment()
we don't know if etna==2.0 comes soon 
so I would love to save full compatibility with old catboost models before it happens

2022-07-04 10:13 UTC, Mr-Geekman commented on etna/models/catboost.py
>      >>> model = CatBoostModelPerSegment()
It is a docstring example to a new class. Why should we use here and old one?
I think that example docstring for the old class should be in the old class.

2022-07-04 10:15 UTC, julia-shenshina commented on etna/models/catboost.py
>      >>> model = CatBoostModelPerSegment()
sorry, I was sure it was about old one
ok

2022-07-04 10:59 UTC, julia-shenshina commented on etna/models/catboost.py
>      >>> model = CatBoostModelMultiSegment()
fixed

2022-07-04 11:00 UTC, julia-shenshina commented on etna/models/catboost.py
>      >>> model = CatBoostModelPerSegment()
fixed

2022-07-05 10:31 UTC, martins0n requested changes
You should add record to CHANGELOG.md

2022-07-05 10:39 UTC, Mr-Geekman approved these changes

2022-07-05 10:40 UTC, martins0n approved these changes

2022-07-05 10:50 UTC, merged