Issue #727
tinkoff-ai/etna pull request #795
Opened 2022-07-13 12:47 UTC by DBcreator

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [ ] Did you write any new necessary tests?
- [x] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes

## Closing issues

2022-07-13 15:41 UTC, Mr-Geekman requested changes
1. Add examples.
2. Improve `plot_feature_relevance ` instead of creating a new plot function.

2022-07-14 17:46 UTC, DBcreator commented
```python3
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from etna.analysis import plot_feature_relevance
from etna.datasets import TSDataset
from etna.analysis import StatisticsRelevanceTable
from etna.transforms import (
    LagTransform,
    FourierTransform
)


def main():
    df = pd.read_csv("examples/data/example_dataset.csv", parse_dates=["timestamp"])
    df_wide = TSDataset.to_dataset(df)
    ts = TSDataset(df=df_wide, freq="D")
    lags = LagTransform(in_column="target", lags=list(range(10, 17)), out_column="lags")
    fourier = FourierTransform(period=360.25, order=4)
    ts.fit_transform([lags,fourier])
    
    relevance_table = StatisticsRelevanceTable()
    plot_feature_relevance(
        ts=ts,
        mode='p-values',
        relevance_table=relevance_table,
        relevance_aggregation_mode="per-segment",
        alpha = 0.05,
        top_k=20, 
    )
    plt.savefig("Per-segment p-values")
    plot_feature_relevance(
        ts=ts,
        mode='p-values',
        relevance_table=relevance_table,
        relevance_aggregation_mode="mean",
        alpha = 0.05,
        top_k=20, 
    )
    plt.savefig("Mean p-values")
    



if __name__ == "__main__":



    main()
```
Per-segment:
![Per-segment p-values](https://user-images.githubusercontent.com/45318525/179048771-0ee1def8-c67c-49d4-a24a-7d33026b9d03.png)
Mean:
![Mean p-values](https://user-images.githubusercontent.com/45318525/179048780-dbdce583-6b31-441b-b179-67cfd058fff4.png)

2022-07-15 09:28 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +            ax.set_title("P-values relevance:")  # type: ignore
Where is `ax.grid()` like for `else` block below?

2022-07-15 09:28 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +    alpha:
This parameter is relevant only for `StatisticsRelevanceTable`, we should emphasize it in documentation.

2022-07-15 09:29 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +    mode: Union[Literal["relevance"], Literal["p-values"]],
Do we really need this parameter? According to the code the mode is determined by the type of `relevance_table`.

2022-07-15 09:30 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +    relevance_table: Union[RelevanceTable, StatisticsRelevanceTable],
We should explain in documentation that logic behind this two types of tables are different and different values are shown.

2022-07-15 15:01 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +    relevance_table: Union[RelevanceTable, StatisticsRelevanceTable],
Remain here `relevance_table: RelevanceTable`. It is a supertype for both `StatisticsRelevanceTable` and `ModelRelevanceTable`

2022-07-15 15:09 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +        RelevanceTable uses relevance table with feature importance from model
Here probably `ModelRelevanceTable` is meant.

According to the [rendered documentation](https://deploy-preview-795--etna-docs.netlify.app/api/etna.analysis.plotters.plot_feature_relevance.html?highlight=plot_feature_relevance#etna.analysis.plotters.plot_feature_relevance) (you can find the link in conversation of this PR), this part is rendered in a single line, it is not nice.

Read in our contribution guide about formatting documentation according to ReST markup language.

I would suggest to write it like this:
```
relevance_table:
        method to evaluate the feature relevance;

        * if :py:class:`~etna.analysis.feature_relevance.relevance.StatisticsRelevanceTable` table is used then relevances are normalized p-values

        * if :py:class:`~etna.analysis.feature_relevance.relevance.ModelRelevanceTable` table is used then relevances are importances from some model

```

2022-07-15 15:10 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +        significance level, default alpha = 0.05, only for StatisticsRelevanceTable
not StatisticsRelevanceTable but :py:class:`~etna.analysis.feature_relevance.relevance.StatisticsRelevanceTable` it will render nicely in the code

2022-07-15 15:51 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +            if type(relevance_table) is StatisticsRelevanceTable:
Checking type is bad, better to check `isinstance(relevance_table, StatisticsRelevanceTable)`

2022-07-15 16:06 UTC, Mr-Geekman commented on etna/analysis/plotters.py
>      normalized:
I think it is strange that we don't use this property if `StatisticsRelevanceTable` is used. Probably we should normalize to sum up to 1 in this case too.

2022-07-15 16:07 UTC, Mr-Geekman commented on etna/analysis/plotters.py
>      normalized:
Or we should mark that these value is used only for `ModelRelevanceTable`.

2022-07-15 16:29 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +    relevance_table: Union[RelevanceTable, StatisticsRelevanceTable],
I think that we should keep this parameter but in `get_fictitious_pvalues` make normalization for sum up to 1 by default.

2022-07-19 06:54 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +    Convert p-values into fictitious variables, with function f(x) = 1 - x.
Add blank line after this line. Below we have extended description that should be separated.

2022-07-19 06:55 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +        significance level, default alpha = 0.05
Add blank line after this line.

2022-07-19 06:56 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +    For StatisticsRelevanceTable also plot vertical line: fictitious significance level.
```
:py:class:`~etna.analysis.feature_relevance.relevance.StatisticsRelevanceTable`
```

2022-07-19 06:58 UTC, Mr-Geekman commented on etna/analysis/plotters.py
>              relevance = relevance_df.loc[segment].sort_values(ascending=is_ascending)
I think like `is_ascending` isn't necessary here anymore.

2022-07-19 07:01 UTC, Mr-Geekman commented on etna/analysis/plotters.py
> +            if normalized and not isinstance(relevance_table, StatisticsRelevanceTable):
Why don't we make normalization for `StatisticsRelevanceTable`?

2022-07-19 14:50 UTC, merged