Speed up columns slices
tinkoff-ai/etna pull request #900
Opened 2022-09-01 14:32 UTC by Mr-Geekman

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [x] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes
Look #775.

## Closing issues
Closes #775.

2022-09-04 20:55 UTC, martins0n requested changes
Maybe we should benchmarks? 
Sorts everywhere could lead to bottlenecks.

2022-09-04 20:55 UTC, martins0n commented on .github/workflows/test.yml
> +      - name: Load cached venv
We shouldn't use cache there -- it could be corrupted.

2022-09-04 20:55 UTC, martins0n commented on .github/workflows/test.yml
> +      - name: Install dependencies
<img width="374" alt="image" src="https://user-images.githubusercontent.com/33594071/188332279-c0729311-f843-4626-9394-58ca86e020a9.png">

As a result of caching we will run the same test case without pandas installing.

2022-09-04 20:55 UTC, martins0n commented on .github/workflows/test.yml
> +          poetry add "pandas${{ matrix.pandas-version }}"
I guess installing via `poetry add` will lead to long dependency resolving.

We should install it via pip after poetry install.

2022-09-04 20:55 UTC, martins0n commented on make_bug.py
> +import numpy as np
Hm, what is the purpose of this script?

2022-09-04 20:55 UTC, martins0n commented on etna/transforms/math/statistics.py
> +        df_slice = df.loc[pd.IndexSlice[:], pd.IndexSlice[:, self.in_column]].sort_index(axis=1)
I guess, we don't need `pd.IndexSlice[:]`

2022-09-06 07:27 UTC, Mr-Geekman commented
I added report with benchmark into `etna-experiments`, PR: `ISSUE - 775`.

2022-09-06 16:51 UTC, martins0n approved these changes
👍

2022-09-07 07:31 UTC, martins0n approved these changes

2022-09-07 08:01 UTC, merged