Implement `predict` in ensembles
tinkoff-ai/etna pull request #972
Opened 2022-10-03 15:58 UTC by Mr-Geekman

## Before submitting (must do checklist)

- [x] Did you read the [contribution guide](https://github.com/tinkoff-ai/etna/blob/master/CONTRIBUTING.md)?
- [x] Did you update the docs? We use Numpy format for all the methods and classes.
- [x] Did you write any new necessary tests?
- [ ] Did you update the [CHANGELOG](https://github.com/tinkoff-ai/etna/blob/master/CHANGELOG.md)?

## Proposed Changes
Look #959.

## Closing issues
Closes #959.

2022-10-04 15:20 UTC, alex-hse-repository requested changes

2022-10-04 15:20 UTC, alex-hse-repository commented on tests/test_ensembles/test_stacking_ensemble.py
> +    naive_ensemble.fit(example_tsds)
Why do you call `fit` two times?

2022-10-04 15:20 UTC, alex-hse-repository commented on tests/test_ensembles/test_stacking_ensemble.py
> +def test_predict_calls_vote(example_tsds: TSDataset, naive_ensemble):
The same with naming here

2022-10-04 15:20 UTC, alex-hse-repository commented on tests/test_ensembles/test_stacking_ensemble.py
> +    naive_ensemble.fit(example_tsds)
And double fit

2022-10-04 15:20 UTC, alex-hse-repository commented on tests/test_ensembles/test_voting_ensemble.py
> -    forecast = ensemble.forecast()
Why do we need to replace `forecast` with it's implementation?

2022-10-04 15:20 UTC, alex-hse-repository commented on tests/test_ensembles/test_voting_ensemble.py
> -    forecast = ensemble.forecast()
The same here

2022-10-04 15:20 UTC, alex-hse-repository commented on tests/test_ensembles/test_voting_ensemble.py
> +    ensemble._vote = MagicMock()
Do we actually need MagicMock here, why not just Mock?

2022-10-04 15:33 UTC, Mr-Geekman commented on tests/test_ensembles/test_stacking_ensemble.py
> +    naive_ensemble.fit(example_tsds)
Mistake, will be fixed.

2022-10-04 15:33 UTC, Mr-Geekman commented on tests/test_ensembles/test_stacking_ensemble.py
> +def test_forecast_calls_vote(example_tsds: TSDataset, naive_ensemble):
Mistake, will be fixed.

2022-10-05 06:26 UTC, alex-hse-repository commented on tests/test_ensembles/test_voting_ensemble.py
> +    ensemble._vote = MagicMock()
As i understand MagicMock is useful testing the magic methods, but here we don't need it

2022-10-05 06:29 UTC, alex-hse-repository approved these changes

2022-10-05 06:30 UTC, merged